import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Buy me a Coffee",
  description: "Generated by create next app",

  icons: {
    icon: [
      {
        rel: "icon",
        type: "image/png",
        url: "/images/favicon.png",
      },
    ]
  }
}


export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className="h-screen w-screen bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px] overflow-x-hidden text-white">
          <SessionWrapper>
            <Navbar />
            <div className="min-h-[83.6vh]">
              <NextTopLoader color="linear-gradient(54deg, rgba(137,61,236,1) 17%, rgba(111,84,239,1) 54%)" />
              {children}
            </div>
            <Footer />
          </SessionWrapper>
        </body>
      </html>
    );
}
